export const UPDATE_POSTS = 'UPDATE_POSTS';
// login actions types
export const LOGIN_START = 'LOGIN_START'; // HERE WE ARE RESSTRCTING THE LOGIN AND MAKING THE LOGNIN BUTTON TO STOP WORK TEMPRORLY UNTILL THE RESPONSE COMES
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
